task: "infovqa_test_reasoning"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.infovqa_doc_to_visual
doc_to_text: !function utils.infovqa_doc_to_text
doc_to_messages: !function utils.infovqa_reasoning_doc_to_messages
doc_to_target: "answers"
process_results: !function utils.infovqa_reasoning_test_process_results
metric_list:
  - metric: submission
    aggregation: !function utils.infovqa_reasoning_test_aggregate_results
    higher_is_better: true
generation_kwargs:
  max_new_tokens: 49152
  temperature: 0
  do_sample: False
include: ../_default_template_infovqa_yaml
