dataset_path: nyu-visionx/CV-Bench
dataset_name: "2D"
task: "cv_bench_2d_reasoning"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.cv_bench_doc_to_visual
doc_to_text: !function utils.cv_bench_doc_to_text
doc_to_messages: !function utils.cv_bench_reasoning_doc_to_messages
doc_to_target: "answer"
process_results: !function utils.cv_bench_reasoning_process_results

metric_list:
  - metric: cv_bench_acc_score
    aggregation: mean
    higher_is_better: true
  - metric: cv_bench_format_score
    aggregation: mean
    higher_is_better: true

generation_kwargs:
  max_new_tokens: 49152

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  version: 0.0
