task: "voxpopuli_en_accented"
dataset_name: "en_accented"
test_split: test
include: _default_template_yaml
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
    audio_column: "audio"
    text_column: "normalized_text"

process_results: !function utils.voxpopuli_process_results_asr

metric_list:
  - metric: wer
    aggregation: mean
    higher_is_better: false
