# VideoMME Number Option Setting
# Change option labels from A.B.C.D to 1.2.3.4 to test format adaptability

task: videomme_number_option
include: ../_default_template_yaml
process_docs: !function utils.videomme_process_docs_number_option
doc_to_text: !function utils.videomme_doc_to_text_number
doc_to_target: "answer"
process_results: !function utils.videomme_process_results_number
metric_list:
  - metric: videomme_perception_score
    aggregation: !function utils.videomme_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's number from the given choices directly."
