dataset_path: Jialuo21/PAIBench-U
dataset_kwargs:
  token: True
  cache_dir: paibench-u
  video: True
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
task: paibench_u
test_split: test
output_type: generate_until
doc_to_visual: !function utils.paibench_u_doc_to_visual
doc_to_text: !function utils.paibench_u_doc_to_text
doc_to_target: "answer"
process_results: !function utils.paibench_u_process_results
metric_list:
  - metric: paibench_u_perception_score
    aggregation: !function utils.paibench_u_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nOnly give the best option.\nBest option: ("
  plm:
    pre_prompt: ""
    post_prompt: "\nOnly give the best option."
