task: "jmmmu_pro_standard_cot"
dataset_path: JMMMU/JMMMU-Pro
dataset_name: standard
test_split: test
output_type: generate_until
doc_to_visual: !function utils.jmmmu_pro_doc_to_visual
doc_to_text: !function utils.jmmmu_pro_doc_to_text
doc_to_target: "{{answer}}"
# The return value of process_results will be used by metrics
process_results: !function utils.jmmmu_pro_process_results

metric_list:
  - metric: jmmmu_pro_acc
    aggregation: !function utils.jmmmu_pro_aggregate_results
    higher_is_better: true


lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "次の選択式問題に答えてください。あなたの回答の最終行は、次の形式にしてください：'答え: $LETTER'（引用符なし）。ここで LETTER は選択肢のいずれかの文字です。答える前に step by step で考えてください。"

generation_kwargs:
  max_new_tokens: 4096

metadata:
  version: 0.0
  interleaved_format: false