task: "jmmmu_pro_vision_cot"
dataset_path: JMMMU/JMMMU-Pro
dataset_name: vision
test_split: test
output_type: generate_until
doc_to_visual: !function utils.jmmmu_pro_doc_to_visual
doc_to_text: "あなたの役割は画像で与えられた問題を解くことです。あなたの回答の最終行は、次の形式にしてください：'答え: $LETTER'（引用符なし）。ここで LETTER は選択肢のいずれかの文字です。答える前に step by step で考えてください。"
doc_to_target: "{{answer}}"
# The return value of process_results will be used by metrics
process_results: !function utils.jmmmu_pro_process_results

metric_list:
  - metric: jmmmu_pro_acc
    aggregation: !function utils.jmmmu_pro_aggregate_results
    higher_is_better: true

generation_kwargs:
  max_new_tokens: 4096

metadata:
  version: 0.0
  interleaved_format: false