group: mathvista_testmini
task:
  - mathvista_testmini_cot
  - mathvista_testmini_solution
  - mathvista_testmini_format
metadata:
  version: 0.0
  gpt_eval_model_name: "gpt-5-nano"
  quick_extract: false