task: wildvision_0617
dataset_name: release_bench_0617_with_modelresponse 
test_split: test500
output_type: generate_until
include: _default_template_yaml
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  aria:
    pre_prompt: "Please provide a detailed answer on the following user instruction:\n"
    post_prompt: ""
  local_infer_dataset_path:
  
