dataset_path: csv
dataset_kwargs:
  token: True
  cache_dir: countix_kekeyeah
  data_files:
    train: https://huggingface.co/datasets/kekeYeah/Countix-QA/resolve/main/cut_countix_train.csv
    validation: https://huggingface.co/datasets/kekeYeah/Countix-QA/resolve/main/cut_countix_val.csv
    test: https://huggingface.co/datasets/kekeYeah/Countix-QA/resolve/main/cut_countix_test.csv
task: countix
test_split: test
output_type: generate_until
doc_to_visual: !function utils.countix_doc_to_visual
doc_to_text: !function utils.countix_doc_to_text
doc_to_target: !function utils.countix_doc_to_target
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: false
process_results: !function utils.countix_process_results
metric_list:
  - metric: mae_norm
    aggregation: mean
    higher_is_better: false
  - metric: obo
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with a single integer."
metadata:
  - version: 0.0
