dataset_name: "Generation"
task: "worldvqa_gen"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.worldvqa_doc_to_visual
doc_to_text: !function utils.worldvqa_doc_to_text
doc_to_target: !function utils.worldvqa_doc_to_answer
process_results: !function utils.worldvqa_process_results
metric_list:
  - metric: submission
    aggregation: !function utils.worldvqa_aggregate_gen
    higher_is_better: true
  - metric: gpt_eval
    aggregation: !function utils.worldvqa_gen_gpt_eval
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
include: _default_template_yaml
