dataset_path: moonshotai/WorldVQA
dataset_kwargs:
  token: False
task: "worldvqa"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.worldvqa_doc_to_visual
doc_to_text: !function utils.worldvqa_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer briefly."
metadata:
  version: 0.0
