dataset_path: suyc21/VMCBench
local_dataset_path:
dataset_kwargs:
  token: True
task: "vmcbench"
test_split: dev
output_type: generate_until
doc_to_visual: !function utils.vmcbench_doc_to_visual
doc_to_text: !function utils.vmcbench_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.vmcbench_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: general
    aggregation: !function utils.vmcbench_aggregate_results
    higher_is_better: true
  - metric: reason
    aggregation: !function utils.vmcbench_aggregate_results
    higher_is_better: true
  - metric: doc
    aggregation: !function utils.vmcbench_aggregate_results
    higher_is_better: true
  - metric: ocr
    aggregation: !function utils.vmcbench_aggregate_results
    higher_is_better: true
  - metric: average
    aggregation: !function utils.vmcbench_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer with the option's letter from the given choices directly.\n"
  local_infer_dataset_path:
metadata:
  - version: 0.0
