# VideoMME Revert OE MCQ Setting
# Convert MCQ to open-ended question (remove options)

task: videomme_revert_oe_mcq
include: ../_default_template_yaml
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
process_results: !function utils.process_results
metric_list:
  - metric: acc_score
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nPlease answer the question with a short answer."
