task: "docvqa_val_reasoning"
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.docvqa_doc_to_visual
doc_to_text: !function utils.docvqa_doc_to_text
doc_to_messages: !function utils.docvqa_reasoning_doc_to_messages
doc_to_target: "answers"
process_results: !function utils.docvqa_reasoning_process_results
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
  - metric: anls_format_score
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  max_new_tokens: 49152
  temperature: 0
  do_sample: False
include: ../_default_template_docvqa_yaml
