
dataset_path: MUIRBENCH/MUIRBENCH
task: "muirbench"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.muir_doc_to_visual
doc_to_text: !function utils.muir_doc_to_text
doc_to_target: !function utils.muir_doc_to_target
process_results: !function utils.muir_process_results
  
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."


generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.MultiChoiceRegexFilter
        group_select: 0
        ignore_case: true
        ignore_punctuation: true
        regex_pattern: "([A-Z])\\."

metric_list:
  - metric: muirbench_score_overall
    aggregation: !function utils.muir_aggregation 
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true

metadata:
  - version: 0.0
