# VideoMMMU Perception GT None Option Setting
dataset_name: "Perception"
task: "video_mmmu_perception_gt_none_option"
test_split: test
output_type: generate_until
process_docs: !function utils.videommmu_process_docs_gt_none
doc_to_visual: !function utils.videommmu_doc_to_visual
doc_to_text: !function utils.videommmu_doc_to_text_perception_comprehension
doc_to_target: !function utils.videommmu_doc_to_answer
process_results: !function utils.videommmu_process_results
metric_list:
  - metric: mmmu_acc
    aggregation: !function utils.videommmu_aggregate_results
    higher_is_better: true
include: _default_template_yaml
