dataset_name: mmh
task: neptune_mmh_v
test_split: test
doc_to_visual: !function utils.neptune_doc_to_visual_video
doc_to_text: !function utils.neptune_doc_to_text
doc_to_target: !function utils.neptune_doc_to_target
process_results: !function utils.neptune_process_results
metric_list:
  - metric: neptune_acc
    aggregation: !function utils.neptune_aggregate_results
    higher_is_better: true
include: _default_template_yaml
