dataset_path: lmms-lab/MMVet
task: "mmvet"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mmvet_doc_to_visual
doc_to_text: "{{question}}" # Such that {{question}} will be replaced by doc["question"]
doc_to_target: "{{answer}}"
generation_kwargs:
  until:
    - "ASSISTANT:"
process_results: !function utils.mmvet_process_results # apply gpt eval here
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mmvet_aggregate_results
    higher_is_better: true
metadata:
  version: 0.0
  gpt_eval_model_name: "gpt-4"