# Copyright 2025 Xiaomi Corporation.

dataset_path: lscpku/OlympiadBench-official
dataset_kwargs:
  token: True
dataset_name: physics_en_all
task : "olympiadbench_physics_en"
test_split: test
output_type: generate_until
doc_to_visual: !function en_utils.olympiadbench_doc_to_visual
doc_to_text: !function en_utils.olympiadbench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16384
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function en_utils.olympiadbench_process_results
metric_list:
  - metric: submission
    aggregation: !function en_utils.olympiadbench_aggregate_results
    higher_is_better: true
  - metric: exact_match
    aggregation: mean
    higher_is_better: true