dataset_path: EtashGuha/JapaneseDocQA
task: "docqa_ja"
output_type: generate_until
test_split: test
doc_to_visual: !function utils.docvqa_doc_to_visual
doc_to_text: !function utils.docvqa_doc_to_text
doc_to_target: "original_answer"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
model_specific_prompt_kwargs:
  default:
    pre_prompt: "\n1 つの単語またはフレーズを使用して質問に答えます。"
    post_prompt: "日本語での回答:"
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
  # - metric: sambajudge
  #   aggregation: mean
  #   higher_is_better: true
  #   query: true