task: "voicebench_bbh"
dataset_name: "bbh"
test_split: test
include: _default_template_yaml
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
    audio_column: "audio"
    source_text_column: "prompt"
    target_text_column: "reference"
    id_column: "id"

process_results: !function utils.voicebench_process_results_bbh

metric_list:
  - metric: accuracy
    aggregation: !function utils.voicebench_aggregate_results
    higher_is_better: true