task: vizwizvqa_val
dataset_path: lmms-lab/VizWiz-VQA
  token: True
test_split: val
output_type: generate_until
doc_to_visual: !function utils.vizwizvqa_doc_to_visual
doc_to_text: !function utils.vizwizvqa_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  until:
    - "ASSISTANT:"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: submission
    aggregation: !function utils.vizwizvqa_aggreate_submissions
    higher_is_better: true
metadata:
  - version: 0.0
  - have_ocr_reference: false
process_results: !function utils.vizwizvqa_process_results
