include: _default_template_yaml

task: omni_robust_bench_std_v
test_split: standard_vision

doc_to_visual: !function utils.omni_robust_doc_to_visual
doc_to_text: !function utils.omni_robust_doc_to_text_vision
doc_to_choice: !function utils.omni_robust_doc_to_choice_vision
doc_to_target: !function utils.omni_robust_doc_to_target

process_results: !function utils.omni_robust_process_results

metadata:
  version: 1.0
  description: "Standard vision questions with correct visual premise"
  modality: vision
  is_misleading: false
