include: _default_template_yaml

task: omni_robust_bench_mis_v
test_split: misleading_vision

doc_to_visual: !function utils.omni_robust_doc_to_visual
doc_to_text: !function utils.omni_robust_doc_to_text_vision
doc_to_choice: !function utils.omni_robust_doc_to_choice_vision
doc_to_target: !function utils.omni_robust_doc_to_target_misleading

process_results: !function utils.omni_robust_process_results_misleading

metadata:
  version: 1.0
  description: "Vision questions with WRONG visual premise - tests robustness"
  modality: vision
  is_misleading: true
