dataset_path: parquet
dataset_kwargs:
  data_files:
    test: "${UNI_MMMU_DATA_DIR}/jigsaw_dataset_2x2ref/*.parquet"
task: "uni_mmmu_jigsaw"
test_split: test
output_type: generate_until

doc_to_visual: !function utils.jigsaw_doc_to_visual
doc_to_text: !function utils.jigsaw_doc_to_text
doc_to_target: "label"

process_results: !function utils.jigsaw_process_results

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true

include: _default_template.yaml
