dataset_path: lmms-lab-eval/UniMMMU
dataset_name: maze
task: "uni_mmmu_maze"
test_split: test
output_type: generate_until

doc_to_visual: !function utils.maze_doc_to_visual
doc_to_text: !function utils.maze_doc_to_text
doc_to_target: "steps"

process_results: !function utils.maze_process_results

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
  - metric: frame_accuracy
    aggregation: mean
    higher_is_better: true

include: _default_template.yaml
