dataset_path: cplou99/FALCON-Bench
dataset_kwargs:
  token: True
  cache_dir: falconbench
  video: True
  force_download: False
  local_files_only: False
test_split: test

task: FALCONBench_mcq
doc_to_visual: !function utils.FALCONbench_doc_to_visual_fullvideo
doc_to_text: !function utils.FALCONbench_doc_to_text_mcq
doc_to_target: "gt_option"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
process_results: !function utils.FALCONbench_process_results_mcq
metric_list:
  - metric: acc
    aggregation: !function utils.FALCONbench_aggregate_results_mcq
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Answer the following question based on the provided frames.\n"
    post_prompt: "Answer with the option's letter from the given choices directly.\n"