task: FALCONBench_oq
doc_to_text: !function utils.FALCONbench_doc_to_text_oq
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  do_sample: False
process_results: !function utils.FALCONbench_process_results_oq
metric_list:
  - metric: gpt_eval_score_acc
    aggregation: !function utils.FALCONbench_aggregate_results_oq 
    higher_is_better: true
include: _default_template_yaml