include: _default_template_yaml
task: mvbench_action_sequence
dataset_name: action_sequence
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_sequence
    post_prompt: "Answer with the option's letter from the given choices directly."