include: _default_template_yaml
task: mvbench_fine_grained_pose
dataset_name: fine_grained_pose
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: fine_grained_pose
    post_prompt: "Only give the best option.\n"
  local_infer_dataset_path: