include: _default_template_yaml
task: mvbench_character_order
dataset_name: character_order
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: character_order
    post_prompt: "Only give the best option.\n"
  local_infer_dataset_path: