include: _default_template.yaml
task: mvbench_object_interaction
dataset_name: object_interaction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: object_interaction
    post_prompt: "Answer with the option's letter from the given choices directly."