include: _default_template_yaml
task: mvbench_state_change
dataset_name: state_change
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: state_change
    post_prompt: "Answer with the option's letter from the given choices directly."