include: _default_template_yaml
task: mvbench_action_count
dataset_name: action_count
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_count
    post_prompt: "Only give the best option.\n"
  local_infer_dataset_path: