include: _default_template_yaml
task: mvbench_action_prediction
dataset_name: action_prediction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_prediction
    post_prompt: "Answer with the option's letter from the given choices directly."