include: _default_template_yaml
task: mvbench_counterfactual_inference
dataset_name: counterfactual_inference
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: counterfactual_inference
    post_prompt: "Only give the best option.\n"
  local_infer_dataset_path: