include: _default_template_yaml
task: mvbench_egocentric_navigation
dataset_name: egocentric_navigation
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: egocentric_navigation
    post_prompt: "Only give the best option.\n"
  local_infer_dataset_path: