"include": "_default_template_vcr_yaml"
dataset_path: vcr-org/VCR-wiki-en-hard-test
task: "vcr_wiki_en_hard"
test_split: train[:100]
process_results: !function utils.vcr_en_process_results
metric_list:
  - metric: vcr_percetion_score
    aggregation: !function utils.vcr_en_process_results
    higher_is_better: true
  - metric: vcr_cognition_score
    aggregation: !function utils.vcr_en_process_results
    higher_is_better: true
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "What is the covered texts in the image? Please restore the covered texts without outputting the explanations."