"include": "_default_template_vcr_yaml"
dataset_path: vcr-org/VCR-wiki-en-hard-test-500
task: "vcr_wiki_en_hard_500"
test_split: test
process_results: !function utils.vcr_en_process_results
metric_list:
  - metric: jaccard
    aggregation: !function utils.vcr_aggregate_results
    higher_is_better: true
  - metric: exact_match
    aggregation: !function utils.vcr_aggregate_results
    higher_is_better: true
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "What is the covered texts in the image? Please restore the covered texts without outputting the explanations."