task: "infovqa_val_lite"
test_split: lite
output_type: generate_until
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
dataset_path: lmms-lab/LMMs-Eval-Lite
dataset_name: infovqa_val 
dataset_kwargs:
  token: True
doc_to_target: "answers"
doc_to_visual: !function utils.infovqa_doc_to_visual
doc_to_text: !function utils.infovqa_doc_to_text
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."