dataset_path: echo840/OCRBench
dataset_kwargs:
  token: True
task: "ocrbench_reasoning"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.ocrbench_doc_to_visual
doc_to_text: !function utils.ocrbench_doc_to_text
doc_to_messages: !function utils.ocrbench_reasoning_doc_to_messages
doc_to_target: "answer"
process_results: !function utils.ocrbench_reasoning_process_results
metric_list:
  - metric: ocrbench_accuracy_acc_score
    aggregation: mean
    higher_is_better: true
  - metric: ocrbench_accuracy_format_score
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  max_new_tokens: 49152
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0
