group: mmupd
task:
  - mmaad_base
  - mmaad_option
  - mmaad_instruction
  - mmiasd_base
  - mmiasd_option
  - mmiasd_instruction
  - mmivqd_base
  - mmivqd_option
  - mmivqd_instruction
metadata:
  version: 0.0
  sys_prompt: ""
  gpt_eval_model_name: "gpt-3.5-turbo-0613"