dataset_path: UnipatAI/BabyVision
task: "babyvision"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.babyvision_doc_to_visual
doc_to_text: !function utils.babyvision_doc_to_text
doc_to_target: !function utils.babyvision_doc_to_target
process_results: !function utils.babyvision_process_results

metric_list:
  - metric: babyvision_acc
    aggregation: !function utils.babyvision_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nThink about the question and give your final answer in \\boxed{Answer} format."
  direct:
    pre_prompt: ""
    post_prompt: "\nPlease answer the question directly."

include: _default_template_yaml

metadata:
  version: 0.1
