# the final score is computed using the script lmms_eval/tasks/mmsearch/get_final_scores.py
# the score file in the submission folder of the three task (end2end, rerank, summarization) should be input as args
dataset_path: CaraJ/MMSearch
dataset_name: end2end
dataset_kwargs:
  token: False
task: "mmsearch_end2end2"
test_split: end2end
output_type: generate_until_multi_round
doc_to_visual: !function lmms_eval_utils.mmsearch_end2end_doc_to_visual
doc_to_text: !function lmms_eval_utils.mmsearch_end2end_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  until:
    - "ASSISTANT:"
  max_new_tokens: 512
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function lmms_eval_utils.mmsearch_end2end_process_results
metric_list:
  - metric: end2end_f1_score
    aggregation: !function lmms_eval_utils.mmsearch_aggregate_results_f1_score
    higher_is_better: true
  - metric: requery_score
    aggregation: !function lmms_eval_utils.mmsearch_aggregate_results_req_score
    higher_is_better: true
lmms_eval_specific_kwargs: # whenever a sample is infered, save it
  middle_resules_dir: mmsearch_logs/mmsearch_middile_results
  result_cache_dir: mmsearch_logs/mmsearch_result_cache_dir
