# the final score is computed using the script lmms_eval/tasks/mmsearch/get_final_scores.py
# the score file in the submission folder of the three task (end2end, rerank, summarization) should be input as args
dataset_path: CaraJ/MMSearch
local_dataset_path:
dataset_name: rerank
dataset_kwargs:
  token: False
task: "mmsearch_rerank"
test_split: rerank
output_type: generate_until
doc_to_visual: !function lmms_eval_utils.mmsearch_rerank_doc_to_visual
doc_to_text: !function lmms_eval_utils.mmsearch_rerank_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  until:
    - "ASSISTANT:"
  max_new_tokens: 1024
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function lmms_eval_utils.mmsearch_rerank_process_results
metric_list:
  - metric: rek_score
    aggregation: !function lmms_eval_utils.mmsearch_aggregate_results_rek_score
    higher_is_better: true
  
lmms_eval_specific_kwargs:
  default:
    shot_type: "format-prompt" # can also be "custom-prompt"
    query_type: "query_wo" # now only support query_wo
  local_infer_dataset_path:
model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original
  llava_onevision:
    image_aspect_ratio: original