group: mathverse_testmini_text
task:
  - mathverse_testmini_text_lite
  - mathverse_testmini_text_dominant
  - mathverse_testmini_text_only
metadata:
  version: 0.0
  gpt_eval_model_name: "gpt-5-nano"
  trunk_response: 30
  quick_match: false