dataset_path: rootsautomation/websrc-test
local_dataset_path:
task: "websrc_test"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.websrc_doc_to_visual
doc_to_text: !function utils.websrc_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.websrc_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
generation_kwargs:
  max_new_tokens: 16
  image_aspect_ratio: pad
metric_list:
  - metric: submission
    aggregation: !function utils.websrc_test_aggregate_results_for_submission
    higher_is_better: true
metadata:
  - version: 0.0