dataset_path: lmms-lab/MMBench_EN
dataset_kwargs:
  token: True
group: mmbench_en
task: "mmbench_en_test"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mmbench_doc_to_visual
doc_to_text: !function utils.mmbench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 256
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function utils.mmbench_process_results
metric_list:
  - metric: submission
    aggregation: !function utils.mmbench_aggregate_test_results
    higher_is_better: true
metadata:
  version: 0.0