dataset_path: tsunghanwu/mscoco_chair
dataset_kwargs:
  token: True
task: "coco_cap_chair"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.coco_cap_chair_doc_to_visual
doc_to_text: !function utils.coco_cap_chair_doc_to_text
doc_to_target: "gt_object"
generation_kwargs:
  max_new_tokens: 2048
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
  until: [] # really important!!! the default would be ["\n\n"] and that will cause truncation

process_results: !function utils.coco_cap_chair_process_result
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: coco_cap_chair_i
    aggregation : !function utils.coco_cap_chair_aggregate_results_chair_i
    higher_is_better : false
  - metric: coco_cap_chair_s
    aggregation : !function utils.coco_cap_chair_aggregate_results_chair_s
    higher_is_better : false

metadata:
  - version: 0.0