dataset_path: lmms-lab/LiveBench
dataset_kwargs:
  token: True
task: "live_bench"
test_split: test
dataset_name: 2024-06
output_type: generate_until
doc_to_visual: !function utils.livebench_doc_to_visual
doc_to_text: !function utils.livebench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.livebench_process_results
metric_list:
  - metric: gpt4_eval_score
    aggregation: !function utils.livebench_aggregate_results
    higher_is_better: true
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  version: "2024-06"
  api_type : openai
  gpt_eval_model_name: "gpt-4o"
