dataset_path: sy1998/MLVU_Test
local_dataset_path:
dataset_kwargs:
  token: True
  cache_dir: mlvu_test
  video: True
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
task: mlvu_test
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mlvu_doc_to_visual_test
doc_to_text: !function utils.mlvu_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.mlvu_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: mlvu_percetion_score
    aggregation: !function utils.mlvu_aggregate_results_test
    higher_is_better: true



