dataset_path: lmms-lab/ChartQAPro
dataset_kwargs:
  token: True
task: "chartqapro"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.chartqapro_doc_to_visual
doc_to_text: !function utils.chartqapro_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False
process_results: !function utils.chartqapro_process_results
metric_list:
  - metric: relaxed_overall
    aggregation: mean
    higher_is_better: true
metadata:
  - version: 0.0
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question with a single word."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"
