dataset_path: NCSOFT/K-MMStar
task: "mmstar_ko"
doc_to_visual: !function utils.mmstar_doc_to_visual
doc_to_text: !function utils.mmstar_doc_to_text
process_results: !function utils.mmstar_process_results_ko
include: _default_template_yaml