dataset_name: L5_6d_spatial
test_split: test
task: spatial457_l5_6d_spatial
include: _default_template_yaml

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
    category: "L5_6d_spatial"
