dataset_name: L3_2d_spatial
test_split: test
task: spatial457_l3_2d_spatial
include: _default_template_yaml

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
    category: "L3_2d_spatial"
