dataset_name: "Intensity"
task: "vitatecs_intensity"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.vitatecs_doc_to_visual
doc_to_text: !function utils.vitatecs_doc_to_text
doc_to_target: !function utils.vitatecs_doc_to_answer
process_results: !function utils.vitatecs_process_results
metric_list:
  - metric: accuracy
    aggregation: !function utils.vitatecs_aggregate_rating
    higher_is_better: true
include: _default_template_yaml
