# LVBench No Visual Setting
# Test model ability to answer without video content

dataset_path: lmms-lab/LVBench
dataset_kwargs:
  token: True
  cache_dir: lvbench
  video: True
test_split: train
task: lvbench_no_visual
output_type: generate_until
doc_to_visual: !function utils.lvbench_doc_to_visual_empty
doc_to_text: !function utils.lvbench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
process_results: !function utils.lvbench_process_results
metric_list:
  - metric: lvbench_score
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question with the option letter"
metadata:
  - version: 0.0
