dataset_path: Hothan/OlympiadBench
dataset_name: OE_MM_physics_en_COMP
dataset_kwargs:
  token: True
task: "olympiadbench_OE_MM_physics_en_COMP"
test_split: train
output_type: generate_until
doc_to_visual: !function testmini_utils.olympiadbench_doc_to_visual
doc_to_text: !function testmini_utils.olympiadbench_doc_to_text
doc_to_target: "final_answer"
generation_kwargs:
  until:
    - "ASSISTANT:"
  max_new_tokens: 16384
  temperature: 1
  top_p: 0.95
  num_beams: 1
  do_sample: true
  repetition_penalty: 1.2
process_results: !function testmini_utils.olympiadbench_process_results
metric_list:
  - metric: llm_as_judge_eval
    aggregation: mean
    higher_is_better: true