# Copyright 2025 Xiaomi Corporation.

dataset_path: lscpku/OlympiadBench-official
dataset_kwargs:
  token: True
dataset_name: physics_en_all
task: olympiadbench_physics_en_reasoning
test_split: test
output_type: generate_until
doc_to_visual: !function utils.olympiadbench_doc_to_visual
doc_to_text: !function utils.olympiadbench_doc_to_text
doc_to_messages: !function utils.olympiadbench_doc_to_messages
doc_to_target: "answer"
process_results: !function utils.olympiadbench_process_results
metric_list:
  - metric: acc_score
    aggregation: mean
    higher_is_better: true
  - metric: format_score
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  max_new_tokens: 49152
metadata:
  - version: 0.0
