dataset_name: "Adaptation"
task: "video_mmmu_adaptation_question_only"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.videoperception_doc_to_visual_question_only
doc_to_text: !function utils.videoperception_doc_to_text_no_preprompt
doc_to_target: !function utils.videoperception_doc_to_answer
process_results: !function utils.videoperception_process_results
metric_list:
  - metric: mmmu_acc
    aggregation: !function utils.videoperception_aggregate_results
    higher_is_better: true
include: _default_template_yaml