dataset_name: "Comprehension"
task: "video_mmmu_comprehension"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.videoperception_doc_to_visual
doc_to_text: !function utils.videoperception_doc_to_text_with_transcript_perception_comprehension
doc_to_target: !function utils.videoperception_doc_to_answer
process_results: !function utils.videoperception_process_results
metric_list:
  - metric: submission
    aggregation: !function utils.videoperception_aggregate_results_for_submission
    higher_is_better: true
  - metric: mmmu_acc
    aggregation: !function utils.videoperception_aggregate_results
    higher_is_better: true
include: _default_template_yaml