dataset_path: json
dataset_kwargs:
  data_files: https://huggingface.co/datasets/ZhaoweiWang/MMLongBench/resolve/main/mmlb_data_example/NIAH/counting-image_test_K128_dep3.jsonl
task: mmlongbench
test_split: train
output_type: generate_until
doc_to_visual: !function utils.mmlongbench_doc_to_visual
doc_to_text: !function utils.mmlongbench_doc_to_text
doc_to_target: answer
generation_kwargs:
  max_new_tokens: 128
  temperature: 0
  do_sample: false
process_results: !function utils.mmlongbench_process_results
metric_list:
  - metric: mmlongbench_acc
    aggregation: !function utils.mmlongbench_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer:"
metadata:
  - version: 0.0
