dataset_path: lmms-lab-eval/RealUnify
dataset_name: attentional_focusing
task: realunify_attentional_focusing
test_split: test
output_type: generate_until
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.doc_to_text
doc_to_target: "answer"
process_results: !function utils.process_results

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false

metric_list:
  - metric: attentional_focusing
    aggregation: !function utils.aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  version: 1.0
