dataset_path: lmms-lab-eval/vggsound
dataset_kwargs:
  token: True
  cache_dir: vggsound
task: vggsound
test_split: test
output_type: generate_until
doc_to_visual: !function utils.vggsound_doc_to_audio
doc_to_text: !function utils.vggsound_doc_to_text
doc_to_target: !function utils.vggsound_doc_to_target
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: false
process_results: !function utils.vggsound_process_results
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the sound class label only."
metadata:
  - version: 0.0
