dataset_path: TIGER-Lab/Mantis-Eval
task: mantis
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mantis_doc_to_visual
doc_to_text: !function utils.mantis_doc_to_text
doc_to_target: !function utils.mantis_doc_to_target
process_results: !function utils.mantis_process_results

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""


generation_kwargs:
  max_new_tokens: 64
  temperature: 0.2
  do_sample: True

metric_list:
  - metric: mantis_score
    aggregation: !function utils.mantis_aggregation
    higher_is_better: true

metadata:
  - version: 0.0
