dataset_path: plnguyen2908/AV-SpeakerBench
dataset_kwargs:
  token: True
  cache_dir: AV-SpeakerBench
  video: True
  revision: "lmms_version"
task: "av_speakerbench_audio"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.av_speakerbench_doc_to_audio
doc_to_text: !function utils.av_speakerbench_doc_to_text_audio
doc_to_target: !function utils.av_speakerbench_doc_to_target
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.av_speakerbench_process_results
metric_list:
  - metric: av_speakerbench_score
    aggregation: !function utils.av_speakerbench_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "The best answer is:"
metadata:
  - version: 0.0
