dataset_path: We-Math/We-Math
output_type: generate_until
doc_to_target: "answer"
metric_list:
  - metric: acc_score
    aggregation: mean
    higher_is_better: true
  - metric: format_score
    aggregation: mean
    higher_is_better: true
  - metric: wemath_loose
    aggregation: !function utils.wemath_aggregate_results_loose
    higher_is_better: true
  - metric: wemath_strict
    aggregation: !function utils.wemath_aggregate_results_strict
    higher_is_better: true

generation_kwargs:
  max_new_tokens: 49152

test_split: testmini
doc_to_messages: !function utils.wemath_doc_to_messages_cot
doc_to_text: !function utils.wemath_doc_to_text_cot
doc_to_visual: !function utils.wemath_doc_to_visual
task: wemath_testmini_reasoning
process_results: !function utils.wemath_reasoning_process_results