dataset_path: vikhyatk/CountBenchQA
task: "countbenchqa"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.countbenchqa_doc_to_visual
doc_to_text: !function utils.countbenchqa_doc_to_text
doc_to_target: "number"
process_results: !function utils.countbenchqa_process_results
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with a single number."
metadata:
  version: 0.0
