task: "covost2_en_zh_dev"
include: _default_template_en_zh_yaml
dataset_path: lmms-lab/covost2_en-zh
local_dataset_path:
dataset_name: en_zh
test_split: dev
lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Translate the speech into Chinese and only output the translation:"
    post_prompt: ""
  qwen2_audio:
    pre_prompt: "Translate the speech into Chinese and only output the translation: <|en|>"
    post_prompt: ""
  local_infer_dataset_path: