dataset_path: floschne/multimodal-m3exam
task: "m3exam_afrikaans"
test_split: afrikaans
output_type: generate_until
doc_to_visual: !function utils.m3exam_doc_to_visual
doc_to_text: !function utils.m3exam_doc_to_text
doc_to_target: "answer_text"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function utils.m3exam_process_results
metric_list:
  - metric: m3exam
    aggregation: !function utils.m3exam_aggregate_results
    higher_is_better: true
metadata:
  - version: 0.0
