dataset_path: ouyanglinke/OmniDocBench_tsv
dataset_kwargs:
  token: True
task: omnidocbench
test_split: train
output_type: generate_until
doc_to_visual: !function utils.omnidocbench_doc_to_visual
doc_to_text: !function utils.omnidocbench_doc_to_text
doc_to_target: !function utils.omnidocbench_doc_to_target
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  do_sample: false
process_results: !function utils.omnidocbench_process_results
metric_list:
  - metric: omnidocbench_exact_match
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with a single word, phrase, or option letter."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"
metadata:
  - version: 0.0
