task: "vqav2"
dataset_path: HuggingFaceM4/VQAv2
test_split: test
output_type: generate_until
doc_to_visual: !function utils.vqav2_doc_to_visual
doc_to_text: !function utils.vqav2_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  until:
    - "ASSISTANT:"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: submission
    aggregation: !function utils.vqav2_aggreate_submissions
    higher_is_better: true
metadata:
  - version: 0.0
process_results: !function utils.vqav2_process_results
