task: "vqav2_val_lite"
dataset_path: lmms-lab/LMMs-Eval-Lite
dataset_name: vqav2_val
dataset_kwargs:
  token: True
output_type: generate_until
doc_to_visual: !function utils.vqav2_doc_to_visual
doc_to_text: !function utils.vqav2_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
metadata:
  - version: 0.0
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
test_split: lite
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils.vqav2_process_results_val
