dataset_path: EtashGuha/HungarianDocQA
task: "docvqa_hu"
output_type: generate_until
test_split: test
doc_to_visual: !function utils.docvqa_doc_to_visual
doc_to_text: !function utils.docvqa_doc_to_text
doc_to_target: "Short Answer"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
model_specific_prompt_kwargs:
  default:
    pre_prompt: "\nVálaszoljon a kérdésre egyetlen szó vagy kifejezés használatával."
    post_prompt: "Válasz magyarul:"
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
  - metric: sambajudge
    aggregation: mean
    higher_is_better: true
    query: true
  - metric: gpt4judge
    aggregation: mean
    higher_is_better: true
    query: true