include: _default_template_yaml
task: "mix_evals_image2text_mc_hard"
dataset_name: "image2text"
test_split: multiple_choice_hard
output_type: generate_until
doc_to_visual: !function utils.mix_evals_image2text_doc_to_visual
doc_to_text: !function utils.mix_evals_image2text_doc_to_text
doc_to_target: "{{reference_answer}}"

generation_kwargs:
  max_new_tokens: 5

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.GPTMultiChoiceFilter
