dataset_path: lmms-lab/llava-wilder
dataset_name: Medium
dataset_kwargs:
  token: True
task: "llava_wilder_medium"
test_split: test
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  xcomposer2_4khd:
    pre_prompt: "[UNUSED_TOKEN_146]user\nQuestion: "
    post_prompt: "[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\n"
include: _default_template_wilder_yaml