dataset_path: daluggas/PRISMM-Bench
dataset_kwargs:
  token: True
task: "prismm_bench_pair_match"
test_split: train
output_type: generate_until
process_docs: !function utils.prismm_pair_match_filter_docs
doc_to_visual: !function utils.prismm_pair_match_doc_to_visual
doc_to_text: !function utils.prismm_pair_match_doc_to_text
doc_to_target: !function utils.prismm_pair_match_doc_to_target
doc_to_messages: !function utils.prismm_pair_match_doc_to_messages
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False
process_results: !function utils.prismm_pair_match_process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"
