include: _default_template_yaml

task: "prismm_bench_identification"
doc_to_visual: !function utils.prismm_doc_to_visual
doc_to_text: !function utils.prismm_doc_to_text
doc_to_target: "answer"
doc_to_messages: !function utils.prismm_doc_to_messages
process_results: !function utils.prismm_process_results
