dataset_path: daluggas/PRISMM-Bench
dataset_kwargs:
  token: True
task: "prismm_bench_identification"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.prismm_doc_to_visual
doc_to_text: !function utils.prismm_doc_to_text
doc_to_target: "answer"
doc_to_messages: !function utils.prismm_doc_to_messages
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False
process_results: !function utils.prismm_process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nOutput only a single letter corresponding to the correct answer. Do not output any explanation or text of the question again."
