include: _default_template_mmbench_reasoning_yaml
task: "mmbench_cn_dev_reasoning"
dataset_name: "cn"
test_split: "dev"
doc_to_text: !function utils.mmbench_cn_doc_to_text
doc_to_messages: !function utils.mmbench_cn_doc_to_messages
process_results: !function utils.mmbench_process_results
metadata:
  version: 0.0
