dataset_path: ling99/OCRBench_v2
dataset_kwargs:
  token: True
task: "ocrbench_v2_reasoning"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.ocrbench_v2_doc_to_visual
doc_to_text: !function utils.ocrbench_v2_doc_to_text
doc_to_messages: !function utils.ocrbench_v2_doc_to_messages
doc_to_target: !function utils.ocrbench_v2_doc_to_target
generation_kwargs:
  max_new_tokens: 49152
process_results: !function utils.ocrbench_v2_process_results_reasoning
metric_list:
  - metric: ocrbench_v2_accuracy
    aggregation: !function utils.ocrbench_v2_aggregate_accuracy
    higher_is_better: true
metadata:
  - version: 0.0
