dataset_path: lmms-lab/RealWorldQA
dataset_kwargs:
  token: True
task: "realworldqa"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.realworldqa_doc_to_visual
doc_to_text: !function utils.realworldqa_doc_to_text
doc_to_target: "answer"

generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.NumberWordsToDigitsFilter
      - function: !function utils.MultiChoiceRegexFilter
        group_select: 0
        ignore_case: true
        ignore_punctuation: true
        regex_pattern: "(\\([A-Z]\\))"

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
      
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  gpt4v:
    pre_prompt: ""
    post_prompt: ""
  xcomposer2_4khd:
    pre_prompt: "[UNUSED_TOKEN_146]user\nQuestion: "
    post_prompt: "[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\nThe answer is"
metadata:
  - version: 0.0
