task: "ami_train"
dataset_name: ihm
test_split: train
include: _default_template_yaml
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
    audio_column: "audio"
    text_column: "text"

process_results: !function utils.ami_process_results_asr

metric_list:
  - metric: wer
    aggregation: mean
    higher_is_better: false
