task: "europal_asr_validation"
test_split: validation
include: _default_template_yaml
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
    audio_column: "audio"
    text_column: "text_verbatim"

process_results: !function utils.europal_asr_process_results_asr

metric_list:
  - metric: wer
    aggregation: mean
    higher_is_better: false
