task: "mmsu"
test_split: test
include: _default_template_yaml

process_results: !function utils.mmsu_process_results

metric_list:
  - metric: accuracy
    aggregation: !function utils.mmsu_aggregate_results
    higher_is_better: true
