# VSP Collision Detection Task (50 samples)
dataset_path: parquet
dataset_kwargs:
  data_files: /blob/lmms-eval-dataset/vsp_collision_50.parquet
task: "vsp_collision"
test_split: train
output_type: generate_until

doc_to_visual: !function utils.collision_doc_to_visual
doc_to_text: !function utils.collision_doc_to_text
doc_to_target: "gt_car"

process_results: !function utils.collision_process_results

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false

metric_list:
  - metric: collision_acc
    aggregation: !function utils.collision_aggregate_results
    higher_is_better: true

metadata:
  version: 1.0
  num_samples: 50
  seed: 42
