# VSP Google Map Navigation Task (50 samples)
dataset_path: parquet
dataset_kwargs:
  data_files: /blob/lmms-eval-dataset/vsp_google_map_50.parquet
task: "vsp_google_map"
test_split: train
output_type: generate_until

doc_to_visual: !function utils.gmap_doc_to_visual
doc_to_text: !function utils.gmap_doc_to_text
doc_to_target: "gt_north_south"

process_results: !function utils.gmap_process_results

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false

metric_list:
  - metric: gmap_acc
    aggregation: !function utils.gmap_aggregate_results
    higher_is_better: true

metadata:
  version: 1.0
  num_samples: 50
  seed: 42
