# VSP Google Map Navigation Task
# Evaluates spatial navigation ability: find a path from S to G
dataset_path: AnonyCAD/VSP
dataset_name: google_map
task: "vsp_google_map"
test_split: test
output_type: generate_until

doc_to_visual: !function utils.gmap_doc_to_visual
doc_to_text: !function utils.gmap_doc_to_text
doc_to_target: "answer"

process_results: !function utils.gmap_process_results

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false

metric_list:
  - metric: gmap_acc
    aggregation: !function utils.gmap_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  version: 1.0
