include: ../_default_template_yaml
task: "vstar_bench_relative_position_reasoning"
dataset_kwargs:
  category: "relative_position"
doc_to_messages: !function utils.vstar_reasoning_doc_to_messages
process_results: !function utils.vstar_reasoning_process_results
generation_kwargs:
  max_new_tokens: 49152
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
metric_list:
  - metric: vstar_relative_position_acc_score
    aggregation: mean
    higher_is_better: true
  - metric: vstar_relative_position_format_score
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
