dataset_path: Cie1/MMSearch-Plus
dataset_kwargs:
  token: False
output_type: generate_until
doc_to_visual: !function utils.mmsearch_plus_doc_to_visual
doc_to_text: !function utils.mmsearch_plus_doc_to_text
doc_to_target: answer
generation_kwargs:
  max_new_tokens: 128
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.mmsearch_plus_process_results
metadata:
  version: 0.0
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or short phrase."
