dataset_path: jordyvl/DUDE_subset_100val
dataset_kwargs:
  token: True
task: dude
test_split: train
output_type: generate_until
doc_to_visual: !function utils.dude_doc_to_visual
doc_to_text: !function utils.dude_doc_to_text
doc_to_target: !function utils.dude_doc_to_target
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  do_sample: false
process_results: !function utils.dude_process_results
metric_list:
  - metric: dude_anls
    aggregation: !function utils.dude_aggregate_anls
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with a single word or phrase."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"
metadata:
  - version: 0.0
